name: schema-migration

on:
  pull_request:
  
jobs:
  schema-migration:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/server
    strategy:
      matrix:
        node-version: [15.x]
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: proyek3
          POSTGRES_USER: proyek3
          POSTGRES_DB: proyek3
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Environment Information
        run: npx envinfo
      - name: Install dependencies
        run: npm ci
      - name: Migrate database
        env:
          DATABASE_HOSTNAME: localhost
          DATABASE_PORT: 5432
          DATABASE_USERNAME: proyek3
          DATABASE_DATABASE: proyek3
          DATABASE_PASSWORD: proyek3
        run: npx sequelize-cli db:migrate